apps/pila_events_web/lib/pila_events_web/router.ex
defmodule PilaEventsWeb.Router do
  use PilaEventsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PilaEventsWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/events", EventController, :list
    get "/events/:id", EventController, :show
  end

  # scope "/events", PilaEventsWeb do
      
  # end

  # Other scopes may use custom stacks.
  # scope "/api", PilaEventsWeb do
  #   pipe_through :api
  # end
end

apps/pila_events_web/lib/pila_events_web/controllers/event_controller.ex
defmodule PilaEventsWeb.EventController do
  use PilaEventsWeb, :controller

  def show(conn, %{"id" => id}) do
    event = PilaEvents.EventQueries.get_by_id(id)
    |> IO.inspect()
    
    render conn, "details.html", event: event
  end

  def list(conn, _params) do
    events = PilaEvents.EventQueries.get_all()
    
    render conn, "list.html", events: events
  end
end

apps/pila_events_web/lib/pila_events_web/controllers/page_controller.ex
defmodule PilaEventsWeb.PageController do
  use PilaEventsWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

apps/pila_events_web/lib/pila_events_web/views/error_view.ex
defmodule PilaEventsWeb.ErrorView do
  use PilaEventsWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

apps/pila_events_web/lib/pila_events_web/views/event_view.ex
defmodule PilaEventsWeb.EventView do
    use PilaEventsWeb, :view
    
    def format_date(date) do
      "#{date.day}-#{date.month}-#{date.year}"
    end
end

apps/pila_events_web/lib/pila_events_web/views/layout_view.ex
defmodule PilaEventsWeb.LayoutView do
  use PilaEventsWeb, :view
end

apps/pila_events_web/lib/pila_events_web/views/page_view.ex
defmodule PilaEventsWeb.PageView do
  use PilaEventsWeb, :view
end

apps/pila_events_web/lib/pila_events_web/views/shared_view.ex
defmodule PilaEventsWeb.SharedView do
    use PilaEventsWeb, :view
    
end

apps/pila_events_web/lib/pila_events_web/templates/event/details.html.eex
<h1><%= @event.title %> <small><%= @event.location %></small></h1>
<h3><%= format_date @event.date %></h3>

apps/pila_events_web/lib/pila_events_web/templates/event/list.html.eex
<h1>All Events</h1>
<%= render PilaEventsWeb.SharedView, "count.html", list: @events %>
<div class="list-group">
    <%= for e <- @events do %>
        <%= render "summary.html", event: e, conn: @conn %>
    <% end %>
</div>

apps/pila_events_web/lib/pila_events_web/templates/event/summary.html.eex
<a href="<%= Routes.event_path(@conn, :show, @event.id) %>">
    <div class="list-group-item">
        <h4 class="list-group-item-heading"><%= @event.title %></h4>
        <span>
            <span class="text-muted">
                <%= @event.location %>
            </span>
            <span class="float-right">
                <strong><%= format_date @event.date %></strong>
            </span>
        </span>
    </div>
</a>

apps/pila_events_web/lib/pila_events_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>PilaEvents · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

apps/pila_events_web/lib/pila_events_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>A productive web framework that<br/>does not compromise speed and maintainability.</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.4/CHANGELOG.md">v1.4 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
    </ul>
  </article>
</section>

apps/pila_events_web/lib/pila_events_web/templates/shared/count.html.eex
<h3>Total Count: <%= Enum.count @list %></h3>